@startmindmap
'https://plantuml.com/mindmap-diagram

caption 限界上下文
title DDD 领域驱动设计

+ 限界上下文
++   通用语言-定义上下文含义
***[#green] 基本
****[#green] 能够简单、清洗、准确描述业务涵义和规则的语言
****[#green] 解决沟通障碍
***[#yellow] 延伸
****[#yellow] 名词
*****[#yellow] 给领域对象命名
*****[#yellow] 商品、订单等，对应实体对象
****[#yellow] 动词
*****[#yellow] 表示动作或事件
*****[#yellow] 商品已下单、订单已付款，对应领域事件或命令
***[#red] 实践
****[#red] 使用表格记录设计过程中产生的领域对象和属性
****[#red] 领域对象在 DDD 分层架构重的位置、属性、依赖关系以及与代码模型对象的映射
****[#red] 如何保证业务模型和代码模型一致
*****[#red] 1. 分析和设计阶段每一个环节保证限界上下文内术语统一
*****[#red] 2. 代码模型设计阶段：建立领域对象和代码对象的一一映射

-- 限界上下文-定义领域边界
--- 基本
---- 封装通用语言和领域对象，提供上下文环境
---- 消除二义性
--- 延伸
---- 示例：能穿多少穿多少
---- 上下文：夏天或冬天，语境不同解释不同
--- 实践
---- 保险业务领域：投保单、保单、批单、赔案
---- 1. 客户投保：投保单实体对象
---- 2. 缴费完成：投保单->保单，系统对应保单实体对象
---- 3. 修改保单：保单->批单，系统对应批单对象
---- 4. 发生理赔：生成赔案，系统有报案实体对象

@endmindmap
