@startmindmap
'https://plantuml.com/mindmap-diagram

caption 领域、子域、核心域、通用域和支撑域
title DDD 领域驱动设计

* 各种域
** 领域
** 子域：按重要性和功能属性划分
*** 核心域(重要性)
**** 业务成功的主要因素和公司的核心竞争力
**** 根据公司业务特点甄别
**** 放在首位
*** 通用域(功能性)
**** 无太多个性化诉求，被多个子域使用的通用功能子域
**** 权限、认证
**** 等等
**** 短信、邮件
*** 支撑域(功能性)
**** 必需、非核心、非通用，即为支持域

@endmindmap
