@startmindmap
'https://plantuml.com/mindmap-diagram

caption 实体和值对象：从领域模型的基础单元看系统设计
title DDD 领域驱动设计

* 实体和值对象
** 基本
*** 领域对象
*** 战略设计向战术设计过度中，形态变化
** 实体
*** 定义
****: 拥有唯一标识，且经历各种状态变更后仍保持一致。
对象的延续性和标识跨域软件生命周期
;
*** 形态
**** 1. 业务形态
***** 战略设计阶段产生
***** 是多个属性、操作或行为的载体
***** 根据命令、操作或事件，找出产生这些行为的业务实体对象
***** 按照业务相关将多个实体对象和值对象聚类，形成聚合

**** 2. 代码形态
***** 实体表现形式是实体类
***** 包含属性和方法
***** 采用充血模型
****** 与实体相关的所有业务逻辑都在实体类的方法中实现
****** 跨多个实体的领域逻辑在领域服务中实现

**** 3. 运行形态
***** 以 DO （领域对象）的形式存在

**** 4. 数据库形态

** 值对象

@endmindmap
