site_name: NahcRaseac's NoteBook
theme:
    name: readthedocs
    custom_dir: custom_theme
nav:
    - 简介: index.md
    - 极客时间:
        - 《DDD 领域驱动设计》: '极客时间/ddd domain design.md'
    - 凤凰架构:
        -  docker 环境配置 : '凤凰架构/docker环境配置.md'
        -  前端工程 : '凤凰架构/前端工程.md'
    - Linux:
        - I/O : 'Linux/io.md'
    - Kubernetes:
        - Install : 'Kubernetes/install.md'
    - 中间件:
        - RocketMQ: 
            - '中间件/RocketMQ/消息去重.md'
            - '中间件/RocketMQ/Golang使用注意事项.md'
    - Blog:
        - 'Blog/自建图床.md'
